### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by clapointe** [thombergs/docx-stamper#32]
File : util/ObjectDeleter.java
When deleting from a cell or the main document, deleted objects are saved as a total, that just gets incremented every time a new deletion is made. When deleting a new object, the line 
`index -= objectsDeletedFrom(table/cell/etc)`
works fine if you happen to be deleting an index above those already deleted, but not otherwise (you'll either get an index out of bounds exception or delete a different element than the one you intended).

Replace that total with a List<Integer> containing deleted indexes.
Use this:
```
   /**
     * Get new index of element to be deleted, taking into account previously deleted elements
     * @param initialIndex initial index of the element to be deleted
     * @param deletedObjects list of indexes of already deleted elements
     * @return
     */
    private int getNewIndex(final int initialIndex, final List<Integer> deletedObjects){
        int newIndex = initialIndex;
        for(Integer deletedIndex : deletedObjects){
            if (deletedIndex < initialIndex){
                newIndex--;
            }
        }
        return newIndex;
    }
```

**Comment by bflorat** [comment]
This is a major issue, please find a docx illustrating the problem
[ConditionalDisplayOfTablesTest.docx](https://github.com/thombergs/docx-stamper/files/2267960/ConditionalDisplayOfTablesTest.docx)

**Comment by bflorat** [comment]
The fix suggested works, PR on the way

**Comment by bflorat** [comment]
Hi, any progress on this ? 

For the record, I just reproduced the issued with the last 1.4.0 release with the sample document ConditionalDisplayOfTablesTest.docx provided before:

```
org.wickedsource.docxstamper.api.DocxStamperException: java.lang.IndexOutOfBoundsException: Index -2 out of bounds for length 131
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:145) ~[docx-stamper-1.4.0.jar:na]
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:118) ~[docx-stamper-1.4.0.jar:na]
	at crtl.geronimo.services.DocumentController.genererDocumentDocx(DocumentController.java:193) ~[classes/:na]
	at crtl.geronimo.services.DocumentController.genererLivrable(DocumentController.java:160) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring
```

PR #46 fixes this. Could you please accept it or fix it another way so we haven't to used a modified library ? It is an big integration pain to use custom patched jars... Thanks.

**Comment by bflorat** [comment]
I forked this project to fix this. It is available on Maven central at
```
  <dependency>
            <groupId>net.florat</groupId>
            <artifactId>docx-stamper</artifactId>
            <version>1.4.0~1</version>
        </dependency>
```

**Comment by bflorat** [comment]
PR sent to the new reference fork repository : https://github.com/verronpro/docx-stamper/pull/19
